### ISSUE TITLE
TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(int32, 1d, C), array(int32, 1d, C), array(float32, 1d, C)

### ISSUE THREAD

**Issue by Huii** [angus924/minirocket#1] opened 2021-01-05 11:15 UTC
Thank you very much, once again, for this great piece of software. Very much appreciated! I'm trying to use it with my data but unfortunately, I always get the following error if I attempt to fit my input with "parameters = fit(x_trainScaled)":

`TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(int32, 1d, C), array(int32, 1d, C), array(float32, 1d, C)`

Here are some, probably, relevant characteristics of my input:
```
    print(x_trainScaled.shape)
    print(x_trainScaled.dtype)
```
returns:
```
(3000, 3000)
float64
```

// edit:

This is the whole traceback:

```
  File "minirocket\code\minirocket.py", line 130, in fit
    biases = _fit_biases(X, dilations, num_features_per_dilation, quantiles)
  File "\lib\site-packages\numba\dispatcher.py", line 500, in _explain_matching_error
    raise TypeError(msg)
```

**Comment by angus924** [comment] 2021-01-06 01:13
Hi, thanks for pointing this out, sorry for the slow response.

The relevant functions take `float32` input.  I think you just need to change your input from `float64` to `float32`, e.g.:

```python
x_trainScaled = x_trainScaled.astype(np.float32)
```

Alternatively, if you want to stick with `float64` you can edit the numba signatures, e.g., for `transform(...)` you would change:

```python
@njit("float32[:,:](float32[:,:],Tuple((int32[:],int32[:],float32[:])))", ...)
```

...to...

```python
@njit("float64[:,:](float64[:,:],Tuple((int32[:],int32[:],float32[:])))", ...)
```

...and so on for all the functions.

I think I went with `float32` because if you are using PyTorch or similar for your classifier (e.g., logistic regression), you're likely going to be using 32-bit floating point by default, so there's no point performing the transform at a higher precision.  However, it doesn't really matter, the input just has to match the numba signature and vice versa.

Does this help?

I've added a comment to the code examples in the readme.

**Comment by Huii** [comment] 2021-01-06 14:07
Hi Angus,

Thank you very much for your fast reply, which was, as usual, spot on. Changing the input type with ".astype(np.float32)" did not work but changing the signatures, as suggested, did. 👍

**Comment by angus924** [comment] 2021-01-06 21:29
Hi @Huii, that's a good start.

A couple of things occur to me:

- It's a bit odd that changing the signatures worked, but changing the data type did not, they are in a sense equivalent.  Did you do the data type conversion for both training and test / validation data?  Would you be willing to share a bit more of your code (from data loading through to classification), so I can try to work out what's going on, if you're comfortable with that?  Either here or through email.  No need to share your data, I would just read through the code to start with.
- I just noticed that you have called your training data `x_trainScaled`.  I assume, possibly incorrectly, that you are normalising your input time series.  Unlike Rocket, MiniRocket does not require the input time series to be normalised.  In fact, it may hurt performance.  By default, we do not normalise input time series for MiniRocket.  However, it may still be necessary for your particular application, it's hard to make a blanket statement here.  I would suggest trying using raw / un-normalised time series first, if this makes sense in your case.

Thanks again for trying out the code, it's really beneficial to get this kind of feedback.

**Comment by Huii** [comment] 2021-01-07 13:03
Hello again @angus924,

Thanks a lot for your reply and your suggestions. You are very right. I did, indeed, not change the type for the test and validation data. My bad. Concerning the normalization: I will try to run the code again without the normalization to see if the performance can be improved.

**Comment by angus924** [comment] 2021-01-07 22:30
> Thanks a lot for your reply and your suggestions. You are very right. I did, indeed, not change the type for the test and validation data. My bad. Concerning the normalization: I will try to run the code again without the normalization to see if the performance can be improved.

Not your fault, the instructions weren't clear.  I've added some additional notes to the readme clarifying these points.

I don't know how well MiniRocket will work for your data.  On average, MiniRocket is more accurate than Rocket on the datasets in the UCR archive, however for any given dataset it might be more accurate, or it might be less accurate (and accuracy might not be the only thing you care about anyway...).  One small suggestion I have is that, if you have very long time series (whatever 'long' means here...), it might be worth trying larger values for the `max_dilations_per_kernel` hyperparameter for the `fit(...)` function (the default value is 32, the largest possible value with 10,000 features is 119).  It is unlikely to make much difference, but it might be worth trying.  The flip side is that compute time will increase to some extent, although this may not be very noticeable in practice.  I would probably only bother trying this if your time series are at least of length 10,000.

**Comment by angus924** [comment] 2021-01-12 02:39
Hi @Huii, I'm going to close this issue.  Let me know if you have any other problems, questions, comments, etc.

**Closed as completed by angus924** 2021-01-12 02:39 UTC

**Comment by Huii** [comment] 2021-01-14 13:54
Hi @angus924,

Sorry for the very late reply. Thank you very much for your support and the useful tips and tricks. I'll let you know if I run into any other problems. Take care.
